name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] 
        py-version: ['3.10',3.11,3.12]
      max-parallel: 2
    runs-on: ${{ matrix.os }} 
    steps:
    - name: Set up Python ${{ matrix.py-version }} on OS ${{ matrix.os }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.py-version }}      
